[project]
name = "pypension"
version = "0.1.0"
description = ""
authors = [
    { name = "bollard", email = "358225+bollard@users.noreply.github.com" }
]
license = "Proprietary"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "matplotlib >= 3.9",
    "numpy >= 2.1",
    "pandas >= 2.2",
    "scipy >= 1.15",
    "seaborn >= 0.13",
    "yfinance >= 0.2",
]

[tool.poetry.group.dev.dependencies]
ruff = "^0.8"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = ["I"] # isort

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
