[tool.poetry]
name = "pypension"
version = "0.1.0"
description = ""
authors = ["bollard <358225+bollard@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.9"
numpy = "^2.1"
pandas = "^2.2"
scipy = "^1.14"
seaborn = "^0.13"
yfinance = "^0.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.7"

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = ["I"] # isort

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
